### ISSUE TITLE
DXYArea-TimeSeries.json中的所有“待明确地区”的currentConfirmedCount均为负值

### ISSUE THREAD

**Issue by SiriusWilliam** [BlankerL/DXY-COVID-19-Crawler#98]
可能是由于confirmCount的值始终为0导致的。
不知如果将其进行绝对值处理的话，数据真实性是否会受到影响。

**Comment by BlankerL** [comment]
你好，我个人建议待明确地区的数量暂时不要理会。下图是丁香园网页上看到的上海市实时疫情数据的数据包。待明确地区的currentConfirmedCount确实为-1。

![image](https://user-images.githubusercontent.com/24969376/78156640-a2d1b400-7471-11ea-9bc1-3c51fa9cf9f0.png)

我针对几条待明确地区为负值的数据进行了简单的计算，发现**待明确地区的各项数值，应该是省级数值减去市级数值后的差值。**

以上海为例，上海市目前的currentConfirmedCount为169，其他明确的区级单位加总后的数值为170，所以待明确地区的数值为-1。

因此，个人建议剔除待明确地区的数值进行分析。

**Comment by BlankerL** [comment]
欢迎大家交流讨论。

**Comment by sirius-william** [comment]
> 
> 
> 你好，我个人建议待明确地区的数量暂时不要理会。下图是丁香园网页上看到的上海市实时疫情数据的数据包。待明确地区的currentConfirmedCount确实为-1。
> 
> ![image](https://user-images.githubusercontent.com/24969376/78156640-a2d1b400-7471-11ea-9bc1-3c51fa9cf9f0.png)
> 
> 我针对几条待明确地区为负值的数据进行了简单的计算，发现**待明确地区的各项数值，应该是省级数值减去市级数值后的差值。**
> 
> 以上海为例，上海市目前的currentConfirmedCount为169，其他明确的区级单位加总后的数值为170，所以待明确地区的数值为-1。
> 
> 因此，个人建议剔除待明确地区的数值进行分析。

你好，感谢解答，我也打算剔除待明确地区的数据了，总感觉如果按绝对值进行处理会有问题，谢谢哈~
